/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2023 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "@coaty/core";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "@coaty/tn-connector",
        version: "1.0.0",
    },
    buildInfo: {
        buildDate: "2023-09-14T13:32:35+02:00",
        buildMode: "development",
    },
    configInfo: {
        serviceHost: "",
    },
};
