name: Create release on pushed version tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            HOWTO.md
            LICENSE
          body_path: ./CHANGELOG.md
